### ISSUE TITLE
Deprecation Warning: Invalid MongoDB Connection URL

### ISSUE THREAD

**Issue by PriyanshuPatel23** [iiitv/Club-Collabaration-backend#11]
![image](https://github.com/user-attachments/assets/9f617bf9-d8ac-42c3-9b06-05935c518600)
While running the application, I encountered a deprecation warning related to the MongoDB connection URL. The above message appeared in the terminal.

**Comment by PriyanshuPatel23** [comment]
@iiitv/nodejs-maintainers I want to work on this issue.

**Comment by Manvitha-Vema** [comment]
if it is not done.could you assign it to me?

**Comment by PriyanshuPatel23** [comment]
@iiitv/nodejs-maintainers could you please add the labels of hacktoberfest and contribute-a-thon.
