### ISSUE TITLE
Schema can be reused

### ISSUE THREAD

**Issue by RohithChittibommala** [iiitv/Club-Collabaration-backend#5]
one schema can be used for both by adding boolean parameter isAdmin
![code2](https://user-images.githubusercontent.com/62145732/94159426-2ad4cb80-fea1-11ea-9c7b-0b7778f47109.png)
![code](https://user-images.githubusercontent.com/62145732/94159429-2c05f880-fea1-11ea-83e8-9de6252d60ce.png)

@anujpuri72  sir can you please assign me the issue

**Comment by anujpuri72** [comment]
@RohithChittibommala  GFI 👍
