### ISSUE TITLE
Models for Event, Club, and Announcement

### ISSUE THREAD

**Issue by JeetJani-11** [iiitv/Club-Collabaration-backend#9]
The backend lacks models for handling the core entities such as Event, Club, and Announcement. Use Mongoose to define schema models for these entities, ensuring they support relationships (e.g., a club can have many events, members, and announcements). Add validation rules where needed.

**Comment by PriyanshuPatel23** [comment]
@iiitv/nodejs-maintainers I want to work on this issue.
